name: Test Adder

on:
  push:
    branches:
      - '**'

jobs:
  test-adder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install

    - name: Run AdderTest
      run: mvn -Dtest=AdderTest test
