name: Run AdderTest on Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Compile Adder and AdderTest
        run: javac -cp .:./lib/junit-4.13.2.jar:./lib/hamcrest-core-1.3.jar src/main/java/Adder.java src/test/java/AdderTest.java

      - name: Run AdderTest
        run: java -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore main.java.AdderTest
